package com.hoang.module.mail.domain;

import com.hoang.app.domain.AbstractEntity;

// Generated Nov 28, 2009 9:50:16 AM by Hibernate Tools 3.2.0.beta8
/**
 * Item generated by hbm2java
 */
public class Item extends AbstractEntity { 

     private static final long serialVersionUID = 1L;

    // Fields    

     private Integer version;
     private String name;
     private String description;
     private String dateCreated;
     private String dateModified;
     private Mailer mailer;
     // Constructors

    /** default constructor */
    public Item() {
    }

    /** full constructor */
    public Item(String name, String description, String dateCreated, String dateModified, Mailer mailer) {
       this.name = name;
       this.description = description;
       this.dateCreated = dateCreated;
       this.dateModified = dateModified;
       this.mailer = mailer;
    }

    // Property accessors
    public Integer getVersion() {
        return this.version;
    }
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    public void setDescription(String description) {
        this.description = description;
    }
    public String getDateCreated() {
        return this.dateCreated;
    }
    public void setDateCreated(String dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getDateModified() {
        return this.dateModified;
    }
    public void setDateModified(String dateModified) {
        this.dateModified = dateModified;
    }
    public Mailer getMailer() {
        return this.mailer;
    }
    public void setMailer(Mailer mailer) {
        this.mailer = mailer;
    }
}
