package com.hoang.module.mail.domain;
// Generated Nov 28, 2009 9:50:16 AM by Hibernate Tools 3.2.0.beta8
import java.util.HashSet;
import java.util.Set;

import com.hoang.app.domain.AbstractEntity;
/**
 * Mail generated by hbm2java
 */
public class Mail extends AbstractEntity { 

     private static final long serialVersionUID = 1L;

    // Fields    

     private Integer version;
     private String host;
     private String username;
     private String password;
     private String senderHost;
     private String senderAddress;
     private String senderName;
     private String subject;
     private Integer timeInterval;
     private Set<Mailer> mailers = new HashSet<Mailer>(0);
     // Constructors

    /** default constructor */
    public Mail() {
    }

	/** minimal constructor */
    public Mail(String host, String username, String password, String senderHost, String senderAddress, String subject, Integer timeInterval) {
        this.host = host;
        this.username = username;
        this.password = password;
        this.senderHost = senderHost;
        this.senderAddress = senderAddress;
        this.subject = subject;
        this.timeInterval = timeInterval;
    }

    /** full constructor */
    public Mail(String host, String username, String password, String senderHost, String senderAddress, String senderName, String subject, Integer timeInterval, Set<Mailer> mailers) {
       this.host = host;
       this.username = username;
       this.password = password;
       this.senderHost = senderHost;
       this.senderAddress = senderAddress;
       this.senderName = senderName;
       this.subject = subject;
       this.timeInterval = timeInterval;
       this.mailers = mailers;
    }

    // Property accessors
    public Integer getVersion() {
        return this.version;
    }
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getHost() {
        return this.host;
    }
    public void setHost(String host) {
        this.host = host;
    }
    public String getUsername() {
        return this.username;
    }
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    public void setPassword(String password) {
        this.password = password;
    }
    public String getSenderHost() {
        return this.senderHost;
    }
    public void setSenderHost(String senderHost) {
        this.senderHost = senderHost;
    }
    public String getSenderAddress() {
        return this.senderAddress;
    }
    public void setSenderAddress(String senderAddress) {
        this.senderAddress = senderAddress;
    }
    public String getSenderName() {
        return this.senderName;
    }
    public void setSenderName(String senderName) {
        this.senderName = senderName;
    }
    public String getSubject() {
        return this.subject;
    }
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public Integer getTimeInterval() {
        return this.timeInterval;
    }
    public void setTimeInterval(Integer timeInterval) {
        this.timeInterval = timeInterval;
    }
    public Set<Mailer> getMailers() {
        return this.mailers;
    }
    public void setMailers(Set<Mailer> mailers) {
        this.mailers = mailers;
    }
}
