package com.hoang.module.mail.domain;
// Generated Nov 28, 2009 9:50:16 AM by Hibernate Tools 3.2.0.beta8
import java.util.HashSet;
import java.util.Set;

import com.hoang.app.domain.AbstractEntity;
/**
 * Mailer generated by hbm2java
 */
public class Mailer extends AbstractEntity { 

     private static final long serialVersionUID = 1L;

    // Fields    

     private Integer version;
     private String name;
     private Set<Item> items = new HashSet<Item>(0);
     private Set<Item> tempItems = new HashSet<Item>(0);
     private Set<Recipient> recipients = new HashSet<Recipient>(0);
     // Constructors

    /** default constructor */
    public Mailer() {
    }

	/** minimal constructor */
    public Mailer(String name) {
        this.name = name;
    }

    /** full constructor */
    public Mailer(String name, Set<Item> items, Set<Recipient> recipients) {
       this.name = name;
       this.items = items;
       this.recipients = recipients;
    }

    // Property accessors
    public Integer getVersion() {
        return this.version;
    }
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public Set<Item> getItems() {
        return this.items;
    }
    public void setItems(Set<Item> items) {
        this.items = items;
    }

    public Set<Item> getTempItems() {
        return tempItems;
    }

    public void setTempItems(Set<Item> tempItems) {
        this.tempItems = tempItems;
    }
    
    public Set<Recipient> getRecipients() {
        return this.recipients;
    }
    public void setRecipients(Set<Recipient> recipients) {
        this.recipients = recipients;
    }
}
