package com.hoang.module.mail.domain;

import com.hoang.app.domain.AbstractEntity;

// Generated Nov 28, 2009 9:50:16 AM by Hibernate Tools 3.2.0.beta8
/**
 * Recipient generated by hbm2java
 */
public class Recipient extends AbstractEntity { 

     private static final long serialVersionUID = 1L;

    // Fields    

     private Integer version;
     private String name;
     private String address;
     private Mailer mailer;
     // Constructors

    /** default constructor */
    public Recipient() {
    }

	/** minimal constructor */
    public Recipient(String name, String address) {
        this.name = name;
        this.address = address;
    }

    /** full constructor */
    public Recipient(String name, String address, Mailer mailer) {
       this.name = name;
       this.address = address;
       this.mailer = mailer;
    }

    // Property accessors
    public Integer getVersion() {
        return this.version;
    }
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    public void setAddress(String address) {
        this.address = address;
    }
    public Mailer getMailer() {
        return this.mailer;
    }
    public void setMailer(Mailer mailer) {
        this.mailer = mailer;
    }
}
