server:
  port: 9090
  jetty:
    queueSize: 50
    minThreads: 10
    maxThreads: 20
    idleTimeout: 30000

datasource:
  models_master:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springrest_jpa
    username: root
    password:
    initialSize: 10
    minIdle: 5
    maxActive: 100
  models_slave:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/springrest_jpa_slave
        username: root
        password:
        initialSize: 10
        minIdle: 5
        maxActive: 100

spring:
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES

logging:
  file: log/app.log
