package com.hvn.spring.model;
// Generated Jan 28, 2015 4:27:18 PM by Hibernate Tools 3.2.2.GA
/**
 * Domain generated by hbm2java
 */
public class Domain extends AbstractEntity { 

     private String code;
     private String name;
    public Domain() {
    }
    public Domain(String code, String name) {
       this.code = code;
       this.name = name;
    }
    public String getCode() {
        return this.code;
    }
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
}
