package com.hvn.spring.model;

// Generated Jan 28, 2015 4:27:18 PM by Hibernate Tools 3.2.2.GA
/**
 * Employee generated by hbm2java
 */
public class Employee extends com.hvn.spring.model.Person implements
		java.io.Serializable {
	private String contractType;
	private Integer salary;

	public Employee() {
	}

	public Employee(String name, String email) {
		super(name, email);
	}

	public Employee(String name, String email, String phone,
			String contractType, Integer salary) {
		super(name, email, phone);
		this.contractType = contractType;
		this.salary = salary;
	}

	public String getContractType() {
		return this.contractType;
	}

	public void setContractType(String contractType) {
		this.contractType = contractType;
	}

	public Integer getSalary() {
		return this.salary;
	}

	public void setSalary(Integer salary) {
		this.salary = salary;
	}
}
