package com.hvn.spring.model;

// Generated Jan 28, 2015 4:27:18 PM by Hibernate Tools 3.2.2.GA
/**
 * Teacher generated by hbm2java
 */
public class Teacher extends com.hvn.spring.model.Person implements
		java.io.Serializable {
	private String degree;
	private Department department;

	public Teacher() {
	}

	public Teacher(String name, String email) {
		super(name, email);
	}

	public Teacher(String name, String email, String phone, String degree,
			Department department) {
		super(name, email, phone);
		this.degree = degree;
		this.department = department;
	}

	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}
}
