package com.hvn.spring.model;
// Generated Jan 28, 2015 4:27:18 PM by Hibernate Tools 3.2.2.GA
import java.util.HashSet;
import java.util.Set;
/**
 * University generated by hbm2java
 */
public class University extends AbstractEntity { 

     private Integer version;
     private String name;
     private String address;
     private String province;
     private String country;
     private String phone;
     private Set departments = new HashSet(0);
     private Set courses = new HashSet(0);
    public University() {
    	
    }
    public University(String name, String address, String province, String country) {
        this.name = name;
        this.address = address;
        this.province = province;
        this.country = country;
    }
    public University(String name, String address, String province, String country, String phone, Set departments, Set courses) {
       this.name = name;
       this.address = address;
       this.province = province;
       this.country = country;
       this.phone = phone;
       this.departments = departments;
       this.courses = courses;
    }
    public Integer getVersion() {
        return this.version;
    }
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    public void setAddress(String address) {
        this.address = address;
    }
    public String getProvince() {
        return this.province;
    }
    public void setProvince(String province) {
        this.province = province;
    }
    public String getCountry() {
        return this.country;
    }
    public void setCountry(String country) {
        this.country = country;
    }
    public String getPhone() {
        return this.phone;
    }
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Set getDepartments() {
        return this.departments;
    }
    public void setDepartments(Set departments) {
        this.departments = departments;
    }
    public Set getCourses() {
        return this.courses;
    }
    public void setCourses(Set courses) {
        this.courses = courses;
    }
}
