package com.hvn.spring.model;
// Generated Jan 28, 2015 4:27:18 PM by Hibernate Tools 3.2.2.GA
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
/**
 * User generated by hbm2java
 */
public class User extends AbstractEntity  {

     private Integer version;
     private String username;
     private String password;
     private String name;
     private String email;
     private Set roles = new HashSet(0);

    /* Spring Security fields*/
    private List<Role> authorities;
    private boolean accountNonExpired = true;
    private boolean accountNonLocked = true;
    private boolean credentialsNonExpired = true;
    private boolean enabled = true;

    public User() {
    }
    public User(String username, String password, String name, String email) {
        this.username = username;
        this.password = password;
        this.name = name;
        this.email = email;
    }
    public User(String username, String password, String name, String email, Set roles) {
       this.username = username;
       this.password = password;
       this.name = name;
       this.email = email;
       this.roles = roles;
    }
    public Integer getVersion() {
        return this.version;
    }
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getUsername() {
        return this.username;
    }
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getRoles() {
        return this.roles;
    }
    public void setRoles(Set roles) {
        this.roles = roles;
    }


}
