package com.hoang.codegenerator.model;
// Generated Nov 20, 2016 3:20:38 PM by Hibernate Tools 3.2.2.GA
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
/**
 * Clazz generated by hbm2java
 */
public class Clazz extends AbstractEntity { 

     private Integer version;
     private String name;
     private Date date;
     private String schedule;
     private Course course;
     private Teacher teacher;
     private Set students = new HashSet(0);
    public Clazz() {
    }
    public Clazz(String name, Date date, String schedule) {
        this.name = name;
        this.date = date;
        this.schedule = schedule;
    }
    public Clazz(String name, Date date, String schedule, Course course, Teacher teacher, Set students) {
       this.name = name;
       this.date = date;
       this.schedule = schedule;
       this.course = course;
       this.teacher = teacher;
       this.students = students;
    }
    public Integer getVersion() {
        return this.version;
    }
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public Date getDate() {
        return this.date;
    }
    public void setDate(Date date) {
        this.date = date;
    }
    public String getSchedule() {
        return this.schedule;
    }
    public void setSchedule(String schedule) {
        this.schedule = schedule;
    }
    public Course getCourse() {
        return this.course;
    }
    public void setCourse(Course course) {
        this.course = course;
    }
    public Teacher getTeacher() {
        return this.teacher;
    }
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }
    public Set getStudents() {
        return this.students;
    }
    public void setStudents(Set students) {
        this.students = students;
    }
}
