package com.hoang.codegenerator.model;
// Generated Nov 20, 2016 3:20:38 PM by Hibernate Tools 3.2.2.GA
/**
 * Course generated by hbm2java
 */
public class Course extends AbstractEntity { 

     private Integer version;
     private String name;
     private Integer credits;
     private Teacher author;
    public Course() {
    }
    public Course(String name, Integer credits) {
        this.name = name;
        this.credits = credits;
    }
    public Course(String name, Integer credits, Teacher author) {
       this.name = name;
       this.credits = credits;
       this.author = author;
    }
    public Integer getVersion() {
        return this.version;
    }
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public Integer getCredits() {
        return this.credits;
    }
    public void setCredits(Integer credits) {
        this.credits = credits;
    }
    public Teacher getAuthor() {
        return this.author;
    }
    public void setAuthor(Teacher author) {
        this.author = author;
    }
}
