package com.hoang.codegenerator.model;
// Generated Nov 20, 2016 3:20:38 PM by Hibernate Tools 3.2.2.GA
/**
 * Department generated by hbm2java
 */
public class Department extends AbstractEntity { 

     private Integer version;
     private String name;
     private String location;
    public Department() {
    }
    public Department(String name, String location) {
       this.name = name;
       this.location = location;
    }
    public Integer getVersion() {
        return this.version;
    }
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getLocation() {
        return this.location;
    }
    public void setLocation(String location) {
        this.location = location;
    }
}
