package com.hoang.codegenerator.model;
// Generated Nov 20, 2016 3:20:38 PM by Hibernate Tools 3.2.2.GA
/**
 * Employee generated by hbm2java
 */
public class Employee extends com.hoang.codegenerator.model.Person implements java.io.Serializable {
     private String contractType;
     private Integer salary;
    public Employee() {
    }
    public Employee(String name, String email) {
        super(name, email);        
    }
    public Employee(String name, String email, String phone, String contractType, Integer salary) {
        super(name, email, phone);        
       this.contractType = contractType;
       this.salary = salary;
    }
    public String getContractType() {
        return this.contractType;
    }
    public void setContractType(String contractType) {
        this.contractType = contractType;
    }
    public Integer getSalary() {
        return this.salary;
    }
    public void setSalary(Integer salary) {
        this.salary = salary;
    }
}
