package com.hoang.codegenerator.model;
// Generated Nov 20, 2016 3:20:38 PM by Hibernate Tools 3.2.2.GA
/**
 * Flower generated by hbm2java
 */
public class Flower extends com.hoang.codegenerator.model.Product implements java.io.Serializable {
     private String type;
     private String color;
    public Flower() {
    }
    public Flower(String sku, String title) {
        super(sku, title);        
    }
    public Flower(String sku, String title, Integer price, String location, String type, String color) {
        super(sku, title, price, location);        
       this.type = type;
       this.color = color;
    }
    public String getType() {
        return this.type;
    }
    public void setType(String type) {
        this.type = type;
    }
    public String getColor() {
        return this.color;
    }
    public void setColor(String color) {
        this.color = color;
    }
}
