package com.hoang.codegenerator.model;
// Generated Nov 20, 2016 3:20:38 PM by Hibernate Tools 3.2.2.GA
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
/**
 * Order generated by hbm2java
 */
public class Order extends AbstractEntity { 

     private Integer version;
     private String number;
     private String customer;
     private String shippingAddress;
     private String billingAddress;
     private String shippingMethod;
     private Date date;
     private Set orderLines = new HashSet(0);
    public Order() {
    }
    public Order(String number, String customer, String shippingAddress, String billingAddress) {
        this.number = number;
        this.customer = customer;
        this.shippingAddress = shippingAddress;
        this.billingAddress = billingAddress;
    }
    public Order(String number, String customer, String shippingAddress, String billingAddress, String shippingMethod, Date date, Set orderLines) {
       this.number = number;
       this.customer = customer;
       this.shippingAddress = shippingAddress;
       this.billingAddress = billingAddress;
       this.shippingMethod = shippingMethod;
       this.date = date;
       this.orderLines = orderLines;
    }
    public Integer getVersion() {
        return this.version;
    }
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getNumber() {
        return this.number;
    }
    public void setNumber(String number) {
        this.number = number;
    }
    public String getCustomer() {
        return this.customer;
    }
    public void setCustomer(String customer) {
        this.customer = customer;
    }
    public String getShippingAddress() {
        return this.shippingAddress;
    }
    public void setShippingAddress(String shippingAddress) {
        this.shippingAddress = shippingAddress;
    }
    public String getBillingAddress() {
        return this.billingAddress;
    }
    public void setBillingAddress(String billingAddress) {
        this.billingAddress = billingAddress;
    }
    public String getShippingMethod() {
        return this.shippingMethod;
    }
    public void setShippingMethod(String shippingMethod) {
        this.shippingMethod = shippingMethod;
    }
    public Date getDate() {
        return this.date;
    }
    public void setDate(Date date) {
        this.date = date;
    }
    public Set getOrderLines() {
        return this.orderLines;
    }
    public void setOrderLines(Set orderLines) {
        this.orderLines = orderLines;
    }
}
