package com.hoang.codegenerator.model;
// Generated Nov 20, 2016 3:20:38 PM by Hibernate Tools 3.2.2.GA
/**
 * OrderLine generated by hbm2java
 */
public class OrderLine extends AbstractEntity { 

     private Integer version;
     private Integer quantity;
     private Product product;
    public OrderLine() {
    }
    public OrderLine(Integer quantity) {
        this.quantity = quantity;
    }
    public OrderLine(Integer quantity, Product product) {
       this.quantity = quantity;
       this.product = product;
    }
    public Integer getVersion() {
        return this.version;
    }
    public void setVersion(Integer version) {
        this.version = version;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Product getProduct() {
        return this.product;
    }
    public void setProduct(Product product) {
        this.product = product;
    }
}
