package com.hoang.codegenerator.model;
// Generated Nov 20, 2016 3:20:38 PM by Hibernate Tools 3.2.2.GA
/**
 * Phone generated by hbm2java
 */
public class Phone extends com.hoang.codegenerator.model.Product implements java.io.Serializable {
     private String model;
     private String made;
    public Phone() {
    }
    public Phone(String sku, String title) {
        super(sku, title);        
    }
    public Phone(String sku, String title, Integer price, String location, String model, String made) {
        super(sku, title, price, location);        
       this.model = model;
       this.made = made;
    }
    public String getModel() {
        return this.model;
    }
    public void setModel(String model) {
        this.model = model;
    }
    public String getMade() {
        return this.made;
    }
    public void setMade(String made) {
        this.made = made;
    }
}
