package com.hoang.codegenerator.model;
// Generated Nov 20, 2016 3:20:38 PM by Hibernate Tools 3.2.2.GA
/**
 * Product generated by hbm2java
 */
public class Product extends AbstractEntity { 

     private Integer version;
     private String sku;
     private String title;
     private Integer price;
     private String location;
    public Product() {
    }
    public Product(String sku, String title) {
        this.sku = sku;
        this.title = title;
    }
    public Product(String sku, String title, Integer price, String location) {
       this.sku = sku;
       this.title = title;
       this.price = price;
       this.location = location;
    }
    public Integer getVersion() {
        return this.version;
    }
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getSku() {
        return this.sku;
    }
    public void setSku(String sku) {
        this.sku = sku;
    }
    public String getTitle() {
        return this.title;
    }
    public void setTitle(String title) {
        this.title = title;
    }
    public Integer getPrice() {
        return this.price;
    }
    public void setPrice(Integer price) {
        this.price = price;
    }
    public String getLocation() {
        return this.location;
    }
    public void setLocation(String location) {
        this.location = location;
    }
}
