package com.hoang.codegenerator.model;
// Generated Nov 20, 2016 3:20:38 PM by Hibernate Tools 3.2.2.GA
/**
 * Role generated by hbm2java
 */
public class Role extends AbstractEntity { 

     private Integer version;
     private String name;
    public Role() {
    }
    public Role(String name) {
       this.name = name;
    }
    public Integer getVersion() {
        return this.version;
    }
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
}
