package com.hoang.codegenerator.model;
// Generated Nov 20, 2016 3:20:38 PM by Hibernate Tools 3.2.2.GA
/**
 * Student generated by hbm2java
 */
public class Student extends Person implements java.io.Serializable {
     private String level;
    public Student() {
    }
    public Student(String name, String email) {
        super(name, email);        
    }
    public Student(String name, String email, String phone, String level) {
        super(name, email, phone);        
       this.level = level;
    }
    public String getLevel() {
        return this.level;
    }
    public void setLevel(String level) {
        this.level = level;
    }
}
