package com.hoang.codegenerator.model;
// Generated Nov 20, 2016 3:20:38 PM by Hibernate Tools 3.2.2.GA
/**
 * Teacher generated by hbm2java
 */
public class Teacher extends Person implements java.io.Serializable {
     private String degree;
     private Department department;
    public Teacher() {
    }
    public Teacher(String name, String email) {
        super(name, email);        
    }
    public Teacher(String name, String email, String phone, String degree, Department department) {
        super(name, email, phone);        
       this.degree = degree;
       this.department = department;
    }
    public String getDegree() {
        return this.degree;
    }
    public void setDegree(String degree) {
        this.degree = degree;
    }
    public Department getDepartment() {
        return this.department;
    }
    public void setDepartment(Department department) {
        this.department = department;
    }
}
