package com.hoang.codegenerator.model;
// Generated Nov 20, 2016 3:20:38 PM by Hibernate Tools 3.2.2.GA
import java.util.HashSet;
import java.util.Set;
/**
 * User generated by hbm2java
 */
public class User extends AbstractEntity { 

     private Integer version;
     private String username;
     private String password;
     private String name;
     private String email;
     private Set roles = new HashSet(0);
    public User() {
    }
    public User(String username, String password, String name, String email) {
        this.username = username;
        this.password = password;
        this.name = name;
        this.email = email;
    }
    public User(String username, String password, String name, String email, Set roles) {
       this.username = username;
       this.password = password;
       this.name = name;
       this.email = email;
       this.roles = roles;
    }
    public Integer getVersion() {
        return this.version;
    }
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getUsername() {
        return this.username;
    }
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getRoles() {
        return this.roles;
    }
    public void setRoles(Set roles) {
        this.roles = roles;
    }
}
