package com.hoang.module.es.domain;
// Generated Jan 3, 2010 10:46:29 AM by Hibernate Tools 3.2.0.beta8
import java.util.HashSet;
import java.util.Set;

import com.hoang.app.domain.AbstractEntity;
/**
 * Event generated by hbm2java
 */
public class Event extends AbstractEntity { 

     private static final long serialVersionUID = 1L;

    // Fields    

     private Integer version;
     private String name;
     private String date;
     private String place;
     private String reserver;
     private Set<Vote> votes = new HashSet<Vote>(0);
     // Constructors

    /** default constructor */
    public Event() {
    }

	/** minimal constructor */
    public Event(String name, String date, String place, String reserver) {
        this.name = name;
        this.date = date;
        this.place = place;
        this.reserver = reserver;
    }

    /** full constructor */
    public Event(String name, String date, String place, String reserver, Set<Vote> votes) {
       this.name = name;
       this.date = date;
       this.place = place;
       this.reserver = reserver;
       this.votes = votes;
    }

    // Property accessors
    public Integer getVersion() {
        return this.version;
    }
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getDate() {
        return this.date;
    }
    public void setDate(String date) {
        this.date = date;
    }
    public String getPlace() {
        return this.place;
    }
    public void setPlace(String place) {
        this.place = place;
    }
    public String getReserver() {
        return this.reserver;
    }
    public void setReserver(String reserver) {
        this.reserver = reserver;
    }
    public Set<Vote> getVotes() {
        return this.votes;
    }
    public void setVotes(Set<Vote> votes) {
        this.votes = votes;
    }
}
