package com.hoang.module.es.domain;

import com.hoang.app.domain.AbstractEntity;

// Generated Jan 3, 2010 10:46:29 AM by Hibernate Tools 3.2.0.beta8
/**
 * Place generated by hbm2java
 */
public class Place extends AbstractEntity { 

     private static final long serialVersionUID = 1L;

    // Fields    

     private Integer version;
     private String name;
     private String activities;
     private String address;
     private String phone;
     // Constructors

    /** default constructor */
    public Place() {
    }

    /** full constructor */
    public Place(String name, String activities, String address, String phone) {
       this.name = name;
       this.activities = activities;
       this.address = address;
       this.phone = phone;
    }

    // Property accessors
    public Integer getVersion() {
        return this.version;
    }
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getActivities() {
        return this.activities;
    }
    public void setActivities(String activities) {
        this.activities = activities;
    }
    public String getAddress() {
        return this.address;
    }
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    public void setPhone(String phone) {
        this.phone = phone;
    }
}
