package com.hoang.module.es.domain;
// Generated Jan 3, 2010 10:46:29 AM by Hibernate Tools 3.2.0.beta8
import java.util.HashSet;
import java.util.Set;

import com.hoang.app.domain.AbstractEntity;
import com.hoang.app.domain.User;
/**
 * Vote generated by hbm2java
 */
public class Vote extends AbstractEntity { 

     private static final long serialVersionUID = 1L;

    // Fields    

     private Integer version;
     private String date;
     private Event event;
     private User user;
     private Set<Place> places = new HashSet<Place>(0);
     // Constructors

    /** default constructor */
    public Vote() {
    }

	/** minimal constructor */
    public Vote(String date) {
        this.date = date;
    }

    /** full constructor */
    public Vote(String date, Event event, User user, Set<Place> places) {
       this.date = date;
       this.event = event;
       this.user = user;
       this.places = places;
    }

    // Property accessors
    public Integer getVersion() {
        return this.version;
    }
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getDate() {
        return this.date;
    }
    public void setDate(String date) {
        this.date = date;
    }
    public Event getEvent() {
        return this.event;
    }
    public void setEvent(Event event) {
        this.event = event;
    }
    public User getUser() {
        return this.user;
    }
    public void setUser(User user) {
        this.user = user;
    }
    public Set<Place> getPlaces() {
        return this.places;
    }
    public void setPlaces(Set<Place> places) {
        this.places = places;
    }
}
