package com.hoang.app.domain;
// Generated Jun 22, 2009 6:25:59 PM by Hibernate Tools 3.2.0.beta8

/**
 * Address generated by hbm2java
 */
public class Address extends AbstractEntity {

     private static final long serialVersionUID = 1L;

    // Fields
     private String street;
     private String city;
     private String phone;
     private String postalOrZipCode;
     private Province province;
     private Country country;
     // Constructors

    /** default constructor */
    public Address() {
    }

    /** full constructor */
    public Address(String street, String city, String phone, String postalOrZipCode, Province province, Country country) {
       this.street = street;
       this.city = city;
       this.phone = phone;
       this.postalOrZipCode = postalOrZipCode;
       this.province = province;
       this.country = country;
    }

    // Property accessors
    public String getStreet() {
        return this.street;
    }
    public void setStreet(String street) {
        this.street = street;
    }
    public String getCity() {
        return this.city;
    }
    public void setCity(String city) {
        this.city = city;
    }
    public String getPhone() {
        return this.phone;
    }
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getPostalOrZipCode() {
        return this.postalOrZipCode;
    }
    public void setPostalOrZipCode(String postalOrZipCode) {
        this.postalOrZipCode = postalOrZipCode;
    }
    public Province getProvince() {
        return this.province;
    }
    public void setProvince(Province province) {
        this.province = province;
    }
    public Country getCountry() {
        return this.country;
    }
    public void setCountry(Country country) {
        this.country = country;
    }
}
