package com.hoang.app.domain;
// Generated Jun 29, 2009 10:26:46 PM by Hibernate Tools 3.2.0.beta8
import java.util.Set;
/**
 * AdminUser generated by hbm2java
 */
public class AdminUser extends User implements java.io.Serializable {

     private static final long serialVersionUID = 1L;

    // Fields
     // Constructors

    /** default constructor */
    public AdminUser() {
    }

	/** minimal constructor */
    public AdminUser(String username, String password) {
        super(username, password);
    }

    /** full constructor */
    public AdminUser(String username, String password, boolean enabled, boolean belongOrganization, String fullname, String email, Party party, Set<UserRole> userRoles) {
        super(username, password, enabled, belongOrganization, fullname, email, party, userRoles);
    }

    // Property accessors
}
