package com.hoang.app.domain;
// Generated Jun 22, 2009 6:25:59 PM by Hibernate Tools 3.2.0.beta8
/**
 * Organization generated by hbm2java
 */
public class Organization extends Party implements java.io.Serializable {

     private static final long serialVersionUID = 1L;

    // Fields    
     private String name;
     private Address address;
     // Constructors

    /** default constructor */
    public Organization() {
    }

	/** minimal constructor */
    public Organization(String name) {
        this.name = name;
    }

    /** full constructor */
    public Organization(String email, String name, Address address) {
        super(email);        
       this.name = name;
       this.address = address;
    }

    // Property accessors
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public Address getAddress() {
        return this.address;
    }
    public void setAddress(Address address) {
        this.address = address;
    }
}
