package com.hoang.app.domain;
// Generated Jun 22, 2009 6:25:59 PM by Hibernate Tools 3.2.0.beta8
/**
 * Province generated by hbm2java
 */
public class Province extends AbstractEntity { 

     private static final long serialVersionUID = 1L;

    // Fields    

     private String code;
     private String name;
     // Constructors

    /** default constructor */
    public Province() {
    }

    /** full constructor */
    public Province(String code, String name) {
       this.code = code;
       this.name = name;
    }

    // Property accessors
    public String getCode() {
        return this.code;
    }
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
}
