package com.hoang.app.domain;
// Generated Jun 22, 2009 6:25:59 PM by Hibernate Tools 3.2.0.beta8
/**
 * Role generated by hbm2java
 */
public class Role extends AbstractEntity { 

     private static final long serialVersionUID = 1L;

    // Fields    

     private Integer version;
     private String name;     
     // Constructors

    /** default constructor */
    public Role() {
    }

    /** full constructor */
    public Role(String name) {
       this.name = name;       
    }

    // Property accessors
    public Integer getVersion() {
        return this.version;
    }
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
}
