package com.hoang.app.domain;
// Generated Jun 22, 2009 6:25:59 PM by Hibernate Tools 3.2.0.beta8
import java.util.Date;
/**
 * UserRole generated by hbm2java
 */
public class UserRole extends AbstractEntity { 

     private static final long serialVersionUID = 1L;

    // Fields    

     private Date expiryDate;
     private Role role;
     // Constructors

    /** default constructor */
    public UserRole() {
    }

	/** minimal constructor */
    public UserRole(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    /** full constructor */
    public UserRole(Date expiryDate, Role role) {
       this.expiryDate = expiryDate;
       this.role = role;
    }

    // Property accessors
    public Date getExpiryDate() {
        return this.expiryDate;
    }
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }
    public Role getRole() {
        return this.role;
    }
    public void setRole(Role role) {
        this.role = role;
    }
}
