package com.hoang.app.domain;
// Generated Jun 29, 2009 10:25:13 PM by Hibernate Tools 3.2.0.beta8
import java.util.HashSet;
import java.util.Set;
/**
 * User generated by hbm2java
 */
public class User extends AbstractEntity {

     private static final long serialVersionUID = 1L;

    // Fields

     private Integer version;
     private String username;
     private String password;
     private boolean enabled;
     private boolean belongOrganization;
     private String fullname;
     private String email;
     private Party party;
     private Set<UserRole> userRoles = new HashSet<UserRole>(0);
     // Constructors

    /** default constructor */
    public User() {
    }

	/** minimal constructor */
    public User(String username, String password) {
        this.username = username;
        this.password = password;
    }

    /** full constructor */
    public User(String username, String password, boolean enabled, boolean belongOrganization, String fullname, String email, Party party, Set<UserRole> userRoles) {
       this.username = username;
       this.password = password;
       this.enabled = enabled;
       this.belongOrganization = belongOrganization;
       this.fullname = fullname;
       this.email = email;
       this.party = party;
       this.userRoles = userRoles;
    }

    // Property accessors
    public Integer getVersion() {
        return this.version;
    }
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getUsername() {
        return this.username;
    }
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    public boolean isBelongOrganization() {
        return this.belongOrganization;
    }
    public void setBelongOrganization(boolean belongOrganization) {
        this.belongOrganization = belongOrganization;
    }
    public String getFullname() {
        return this.fullname;
    }
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getEmail() {
        return this.email;
    }
    public void setEmail(String email) {
        this.email = email;
    }
    public Party getParty() {
        return this.party;
    }
    public void setParty(Party party) {
        this.party = party;
    }
    public Set<UserRole> getUserRoles() {
        return this.userRoles;
    }
    public void setUserRoles(Set<UserRole> userRoles) {
        this.userRoles = userRoles;
    }
}
